from setuptools import setup, find_packages

setup(name='PyCURT',
      version='1.0',
      description='Python-based automated data CUration Workflow for RadioTherapy data',
      url='https://github.com/TransRadOnc-HIT/PyCURT.git',
      python_requires='>=3.5',
      author='Francesco Sforazzini',
      author_email='f.sforazzini@dkfz.de',
      license='Apache 2.0',
      zip_safe=False,
      include_package_data=True,
      install_requires=[
      'matplotlib',
      'nibabel',
      'numpy',
      'pandas==1.0.1',
      'pydicom',
      'pynrrd',
      'torch==1.7.1',
      'torchvision==0.8.2',
      'scikit-image',
      'opencv-python==4.2.0.34',
      'requests',
      'SimpleITK',
      'pyyaml==5.3',
      'MR-class',
      'nipype',
      'core',
      'medpy==0.3.0',
      'batchgenerators',
      'torchio',
      'albumentations'],
      data_files=[('resources', ['resources/random.nii.gz'])],
      dependency_links=['git+https://github.com/TransRadOnc-HIT/nipype.git@c453eac5d7efdd4e19a9bcc8a7f3d800026cc125#egg=nipype-9876543210',
                        'git+https://github.com/TransRadOnc-HIT/core.git#egg=core',
                        'git+https://github.com/TransRadOnc-HIT/MR-class.git#egg=MR-class'],
      entry_points={
          'console_scripts': ['pycurt_gui = scripts.pycurt_gui:main',
			      'pycurt = scripts.pycurt_cmdline:main']},
      packages=find_packages(exclude=['*.tests', '*.tests.*', 'tests.*', 'tests']),
      classifiers=[
          'Intended Audience :: Science/Research',
          'Programming Language :: Python',
          'Topic :: Scientific/Engineering',
          'Operating System :: Unix'
      ]
      )
